### ISSUE TITLE
Edge-case bug with overriding ticker/symbol.

### ISSUE THREAD

**Issue by NewDark90** [tylim88/Crypto-Symbol#16]
### Problem context

Nano recently changed it's ticker to XNO instead of Nano. 

There is currently also a token under XNO called "Xeno Token". 

That, in of itself is fine. I'd like to override the XNO ticker to have a name of "Nano" as I don't care about this particular token. 

### The Bug

[Because the code is basically Object.assign based on the "name-symbol" pair](https://github.com/tylim88/Crypto-Symbol/blob/761fd0edd7e000a0a7e30ba29fee816338053f7f/src/index.ts#L26), it's keying off of the name specifically for an overwrite.

This means it is overriding the ticker for Nano (NANO) to be XNO, the swapKeyAndValue function will hit "XNO": "Nano", and override it to be "XNO": "Xeno Token" as it is further down the list.

**Comment by tylim88** [comment]
why on earth people using the same ticker, I thought it has to be unique according to https://coinmarketcap.com/alexandria/glossary/ticker-symbol

one has to go then...

**Comment by tylim88** [comment]
oh wait, there is a solution to this

**Comment by NewDark90** [comment]
Trust me, I understand annoyance with the weird move here, and it is very recent:
https://medium.com/@nanocurrency/say-hello-to-xno-7ed55e419e3f

**Comment by tylim88** [comment]
I need few days to fix this with backward compatibility, also this library is quite old need major setup upgrade

**Comment by tylim88** [comment]
I decided just do quick fix instead, it doesn't worth the effort for a single edge case

I removed Xeno Token from the list and update Nano ticker to XNO

please install 3.3.3

**Comment by NewDark90** [comment]
Thank you!

Are you able to receive a BAT tip to your github account?

**Comment by tylim88** [comment]
I just created the channel, will let you know when it is ready, thanks
