### ISSUE TITLE
Undeclared dependency

### ISSUE THREAD

**Issue by Myphz** [tylim88/Crypto-Symbol#41]
I'm trying to use this library in my Vite app, but it seems like it needs `axios` as a dependency:

```
✘ [ERROR] Could not resolve "axios"

  node_modules/crypto-symbol/dist/1_sync/1_fetch.js:34:75:
    34 │     const axios = (await Promise.resolve().then(() => __importStar(require('axios')))).default;
       ╵                                                                            ~~~~~~~

  You can mark the path "axios" as external to exclude it from the bundle, which will remove this
  error. You can also surround this "require" call with a try/catch block to handle this failure at
  run-time instead of bundle-time.

8:38:47 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/crypto-symbol/dist/1_sync/1_fetch.js:34:75: ERROR: Could not resolve "axios"
    at failureErrorWithLog (/home/daniel/Documents/JS/wwwallet-fe/node_modules/esbuild/lib/main.js:1600:15)
    at /home/daniel/Documents/JS/wwwallet-fe/node_modules/esbuild/lib/main.js:1246:28
    at runOnEndCallbacks (/home/daniel/Documents/JS/wwwallet-fe/node_modules/esbuild/lib/main.js:1031:63)
    at buildResponseToResult (/home/daniel/Documents/JS/wwwallet-fe/node_modules/esbuild/lib/main.js:1244:7)
    at /home/daniel/Documents/JS/wwwallet-fe/node_modules/esbuild/lib/main.js:1353:14
    at /home/daniel/Documents/JS/wwwallet-fe/node_modules/esbuild/lib/main.js:663:9
    at handleIncomingPacket (/home/daniel/Documents/JS/wwwallet-fe/node_modules/esbuild/lib/main.js:760:9)
    at Socket.readFromStdout (/home/daniel/Documents/JS/wwwallet-fe/node_modules/esbuild/lib/main.js:629:7)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
Vite Error, /node_modules/.vite/deps/crypto-symbol.js?v=2dfff904 optimized info should be defined```

**Comment by Myphz** [comment]
This error appears only on the latest version of the package, i.e `3.5.14`. It didn't occur on version `3.3.4`.

**Comment by tylim88** [comment]
are you trying to use `sync` API?

if so simply install `axios`, no other setting needed

if you are not using `sync` API, you should not see this error as shown in this codesanbox example https://codesandbox.io/s/flamboyant-panini-xqcvqy?file=/src/index.ts:0-45

**Comment by tylim88** [comment]
what vite template are you using by the way, I want to test it

**Comment by tylim88** [comment]
ok you are right, vite will throw missing axios error

it works as expected in create-react-app, but not vite

for now simply install `axios`, I will investigate this

**Comment by tylim88** [comment]
seem like vite default config cannot handle dynamic import

I have no idea how to configure vite as I am not familiar with it

to make thing easier for everyone I change my code instead

now `axios` is a parameter instead of a dynamic module

fix at [commit](https://github.com/tylim88/Crypto-Symbol/commit/81b2538a896664ae0b4f7cfdbd77f525d079bb98)

please install version 3.5.15
