### ISSUE TITLE
Possible to look for multiple tickers in string?

### ISSUE THREAD

**Issue by Diogovski** [tylim88/Crypto-Symbol#49]
Hi, is there a way to get multiple tickers using the symbolLookup() function? i have some strings that have more than 1 ticker on it,
example: 'Price analysis 9/14: BTC, ETH, BNB, XRP, ADA, SOL, DOGE, DOT, MATIC, SHIB'  but when  i run the function it returns undefined.

**Comment by Diogovski** [comment]
If i use the .includes() function while looping for the object of the tickers i am able to get this
'BTC,ETH,BNB,XRP,ADA,SOL,DOGE,DOT,MATIC,SHIB,T,HI,OG,SHI,D,TH,MAT,A,IC,G,O,DOG,BT' 
it returns all the one i need/want, but unfortunately it alsos breaks them appart

**Comment by tylim88** [comment]
you mean `nameLookup`?

not possible to transform multiple ticker, but for your case you can do some parsing
```ts
import { cryptoSymbol } from "crypto-symbol";

const { nameLookup } = cryptoSymbol({});

const longString =
  "Price analysis 9/14: BTC, ETH, BNB, XRP, ADA, SOL, DOGE, DOT, MATIC, SHIB";

const splitted = longString.split(":");

const tickersArr = splitted[1].split(",");

const getNames = tickersArr.reduce((acc, item, index) => {
  return acc + nameLookup(item) + (index === tickersArr.length - 1 ? "" : ", ");
}, splitted[0] + ": "); 
```
![image](https://user-images.githubusercontent.com/5227509/190695402-945991d9-e697-4f01-b15a-423201e3c54b.png)

[codesandbox](https://codesandbox.io/s/busy-moser-919qb4?file=/src/index.ts)

**Comment by Diogovski** [comment]
No i only want to return the tickers/symbols

A sexta, 16/09/2022, 18:22, Acid Coder ***@***.***> escreveu:

**Comment by tylim88** [comment]
can you tell me
what is your input?
what is your expected output?

**Comment by Diogovski** [comment]
my input is different phrases, some only have bitcoin on it, others have other coins on it,
the expected output is the symbols of the coins mentioned on each phrase

**Comment by Diogovski** [comment]
Current input/output
![image](https://user-images.githubusercontent.com/81532541/190702386-e62e8c6a-efaf-4516-ba9e-33abdc113e7b.png)

expected output: only the symbols withput those with only 1,2 char...

**Comment by Diogovski** [comment]
currently using this to get the tickers , since using the getsymbol function doesnt work when trying to get multiple symbols.
![image](https://user-images.githubusercontent.com/81532541/190702532-5af74582-086a-4c09-8937-85266acd9f44.png)

**Comment by tylim88** [comment]
can you post the raw text for this one?

> Current input/output ![image](https://user-images.githubusercontent.com/81532541/190702386-e62e8c6a-efaf-4516-ba9e-33abdc113e7b.png)
> 
> expected output: only the symbols withput those with only 1,2 char...

I will see what I can do tomorrow, bed time now

**Comment by Diogovski** [comment]
[
  ' Bitcoin exchange inflows see biggest one-day spike since March 2020 ',
  ' Possession of Bitcoin still legal in China despite the ban, lawyer says ',
  " El Salvador's pro-Bitcoin president Nayib Bukele announces reelection bid  ",
  ' Celsius requests permission to sell off its stablecoins  ',
  ' Bitcoin price threatens $19.6K as Ray Dalio predicts 30% stocks crash ',
  ' The Ethereum Merge to proof-of-stake is complete — What’s next? | Interview with Dr. Julian Hosp  ',
  " Bitcoin price loses $20K, ETH price drops 8% after 'monumental' Ethereum Merge ",
  ' Crypto for foreign trade: What do we know about Iran’s new strategy ',
  " Norwegian town wants 'noisy' Bitcoin miner out, CEO responds ",
  " Michael Saylor slams 'misinformation' about Bitcoin’s energy use ",
  ' Price analysis 9/14: BTC, ETH, BNB, XRP, ADA, SOL, DOGE, DOT, MATIC, SHIB ',
  " Analyst on $17.6K BTC price bottom: Bitcoin 'not there yet' ",
  ' BTC price clings to $20K as US stocks lose the equivalent of 4 Bitcoin market caps ',
  ' Bitcoin is the perfect settlement layer to build apps on top of: Hiro CEO ',
  ' Bitcoin margin long-to-short ratio at Bitfinex reaches the highest level ever '
]
[
  'BTC',
  'BTC',
  'BTC',
  'CEL',
  'BTC,D,DALI',
  'ETH,T,D',
  'BTC,ETH,T,TH',
  '',
  'BTC,O',
  'BTC',
  'BTC,ETH,BNB,XRP,ADA,SOL,DOGE,DOT,MATIC,SHIB,T,HI,OG,SHI,D,TH,MAT,A,IC,G,O,DOG,BT',
  'BTC,T,A,BT',
  'BTC,T,U,BT',
  'BTC,O',
  'BTC'
]

**Comment by tylim88** [comment]
```ts
import { cryptoSymbol } from "crypto-symbol";

const { symbolLookup, nameLookup } = cryptoSymbol({});

const titleArr = [
  " Bitcoin exchange inflows see biggest one-day spike since March 2020 ",
  " Possession of Bitcoin still legal in China despite the ban, lawyer says ",
  " El Salvador's pro-Bitcoin president Nayib Bukele announces reelection bid ",
  " Celsius requests permission to sell off its stablecoins ",
  " Bitcoin price threatens $19.6K as Ray Dalio predicts 30% stocks crash ",
  " The Ethereum Merge to proof-of-stake is complete — What’s next? | Interview with Dr. Julian Hosp ",
  " Bitcoin price loses $20K, ETH price drops 8% after 'monumental' Ethereum Merge ",
  " Crypto for foreign trade: What do we know about Iran’s new strategy ",
  " Norwegian town wants 'noisy' Bitcoin miner out, CEO responds ",
  " Michael Saylor slams 'misinformation' about Bitcoin’s energy use ",
  " Price analysis 9/14: BTC, ETH, BNB, XRP, ADA, SOL, DOGE, DOT, MATIC, SHIB ",
  " Analyst on $17.6K BTC price bottom: Bitcoin 'not there yet' ",
  " BTC price clings to $20K as US stocks lose the equivalent of 4 Bitcoin market caps ",
  " Bitcoin is the perfect settlement layer to build apps on top of: Hiro CEO ",
  " Bitcoin margin long-to-short ratio at Bitfinex reaches the highest level ever "
];

const answ = titleArr.map((title) => {
  const arr: string[] = [];
  title.split(" ").forEach((word) => {
    const found =
      symbolLookup(word) ||
      symbolLookup(nameLookup(word) || "hsuadhiudhsudhahdi");
    found && arr.push(found);
  });
  return arr;
});
```
![image](https://user-images.githubusercontent.com/5227509/190706375-ea3f93b7-141b-43cb-858a-c6f0ac52728a.png)
[codesandbox](https://codesandbox.io/s/busy-moser-919qb4?file=/src/index.ts)

**Comment by Diogovski** [comment]
thx, its looking better now, i added something so it removes duplicates from the arrays ( mainly BTC ), now gonna try to figure out how to remove those that aren't actually referred as symbols but words

**Comment by tylim88** [comment]
some coin symbol are English word, you can add a list to filter it out
```ts
import { cryptoSymbol } from "crypto-symbol";

const { symbolLookup, nameLookup } = cryptoSymbol({});

const titleArr = [
  " Bitcoin exchange inflows see biggest one-day spike since March 2020 ",
  " Possession of Bitcoin still legal in China despite the ban, lawyer says ",
  " El Salvador's pro-Bitcoin president Nayib Bukele announces reelection bid ",
  " Celsius requests permission to sell off its stablecoins ",
  " Bitcoin price threatens $19.6K as Ray Dalio predicts 30% stocks crash ",
  " The Ethereum Merge to proof-of-stake is complete — What’s next? | Interview with Dr. Julian Hosp ",
  " Bitcoin price loses $20K, ETH price drops 8% after 'monumental' Ethereum Merge ",
  " Crypto for foreign trade: What do we know about Iran’s new strategy ",
  " Norwegian town wants 'noisy' Bitcoin miner out, CEO responds ",
  " Michael Saylor slams 'misinformation' about Bitcoin’s energy use ",
  " Price analysis 9/14: BTC, ETH, BNB, XRP, ADA, SOL, DOGE, DOT, MATIC, SHIB ",
  " Analyst on $17.6K BTC price bottom: Bitcoin 'not there yet' ",
  " BTC price clings to $20K as US stocks lose the equivalent of 4 Bitcoin market caps ",
  " Bitcoin is the perfect settlement layer to build apps on top of: Hiro CEO ",
  " Bitcoin margin long-to-short ratio at Bitfinex reaches the highest level ever "
];

const englishWords = ["layer", "ever", "build", "top", "caps"];

const answ = titleArr.map((title) => {
  const arr: string[] = [];
  const exist: Record<string, boolean> = {};
  title.split(" ").forEach((word) => {
    const isEnglishWord = englishWords.some((eword) => {
      return word.toLowerCase().includes(eword);
    });
    if (!isEnglishWord) {
      const found =
        symbolLookup(word) ||
        symbolLookup(nameLookup(word) || "hsuadhiudhsudhahdi");

      const isDuplicated = exist[`${found}`];
      exist[`${found}`] = true;
      !isDuplicated && found && arr.push(found);
    }
  });
  return arr;
});

console.log(answ);
```

![image](https://user-images.githubusercontent.com/5227509/190838803-a1b13b38-dc47-4e86-8e53-237236c9a540.png)

there is problem with matching text like `bitcoin's`, because this is a lookup library, it can filter out unnecessary character but it cant match the closest text

example:
`bitcoin'` --> `bitcoin` --> found!
`bitcoin's` --> `bitcoins` --> not found!

**Comment by tylim88** [comment]
solved by using regex expression

![image](https://user-images.githubusercontent.com/5227509/190839042-3b278fdc-229b-41ce-84ea-aefdfaf5e41a.png)
```ts
import { cryptoSymbol } from "crypto-symbol";

const { symbolLookup, nameLookup } = cryptoSymbol({});

const titleArr = [
  " Bitcoin exchange inflows see biggest one-day spike since March 2020 ",
  " Possession of Bitcoin still legal in China despite the ban, lawyer says ",
  " El Salvador's pro-Bitcoin president Nayib Bukele announces reelection bid ",
  " Celsius requests permission to sell off its stablecoins ",
  " Bitcoin price threatens $19.6K as Ray Dalio predicts 30% stocks crash ",
  " The Ethereum Merge to proof-of-stake is complete — What’s next? | Interview with Dr. Julian Hosp ",
  " Bitcoin price loses $20K, ETH price drops 8% after 'monumental' Ethereum Merge ",
  " Crypto for foreign trade: What do we know about Iran’s new strategy ",
  " Norwegian town wants 'noisy' Bitcoin miner out, CEO responds ",
  " Michael Saylor slams 'misinformation' about Bitcoin’s energy use ",
  " Price analysis 9/14: BTC, ETH, BNB, XRP, ADA, SOL, DOGE, DOT, MATIC, SHIB ",
  " Analyst on $17.6K BTC price bottom: Bitcoin 'not there yet' ",
  " BTC price clings to $20K as US stocks lose the equivalent of 4 Bitcoin market caps ",
  " Bitcoin is the perfect settlement layer to build apps on top of: Hiro CEO ",
  " Bitcoin margin long-to-short ratio at Bitfinex reaches the highest level ever "
];

const englishWords = ["layer", "ever", "build", "top", "caps"];

const answ = titleArr.map((title) => {
  const arr: string[] = [];
  const exist: Record<string, boolean> = {};
  title.split(/[,.’'\s]/).forEach((word) => {
    const isEnglishWord = englishWords.some((eword) => {
      return word.toLowerCase().includes(eword);
    });
    if (!isEnglishWord) {
      const found =
        symbolLookup(word) ||
        symbolLookup(nameLookup(word) || "hsuadhiudhsudhahdi");

      const isDuplicated = exist[`${found}`];
      exist[`${found}`] = true;
      !isDuplicated && found && arr.push(found);
    }
  });
  return arr;
});
```
